version: "2.0"

services:
  sentient-api:
    image: ghcr.io/toxmon/sentient-api:1.1.3
    env:
      # Secrets set at deploy time: provider-services tx deployment create deploy.yaml
      - "ADMIN_API_KEY=9cf70c42897f7cd393b3a3417c8f9d11b79b01b58368d660f6ab5d63a6a0066b"
      - "IP_HASH_SALT=ad1617032ea8bcbaf18ac7a74ef27c77"
    expose:
      - port: 8000
        as: 80
        to:
          - global: true

profiles:
  compute:
    sentient-api:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 512Mi

  placement:
    any:
      pricing:
        sentient-api:
          denom: uact
          amount: 50

deployment:
  sentient-api:
    any:
      profile: sentient-api
      count: 1
