version: "2.0"

services:
  sentient-api:
    image: ghcr.io/toxmon/sentient-api:1.1.1
    env:
      # Secrets set at deploy time: provider-services tx deployment create deploy.yaml
      - "ADMIN_API_KEY=$ADMIN_API_KEY"
      - "IP_HASH_SALT=$IP_HASH_SALT"
    expose:
      - port: 8000
        as: 80
        to:
          - global: true

profiles:
  compute:
    sentient-api:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 512Mi

  placement:
    any:
      pricing:
        sentient-api:
          denom: uact
          amount: 50

deployment:
  sentient-api:
    any:
      profile: sentient-api
      count: 1
